services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecompanel_api
    ports:
      - '8080:3000'
    environment:
      DATABASE_PORT: 5432
      DATABASE_HOST: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: aYKH8gnMK4ho
      DATABASE_NAME: ecompanel
    command: ['npm', 'run', 'start:dev']
    depends_on:
      - postgres
    volumes:
      - .:/app
    working_dir: /app
  postgres:
    image: postgres:latest
    container_name: ecompanel_pg
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aYKH8gnMK4ho
      POSTGRES_DB: ecompanel
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
